I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00start.rpy", line 190, in script
    python:
  File "renpy/common/00start.rpy", line 191, in <module>
    renpy.execute_default_statement(True)
  File "game/script.rpy", line 19, in set_default
    default lupDate = false
  File "game/script.rpy", line 19, in <module>
    default lupDate = false
NameError: name 'false' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/common/00start.rpy", line 190, in script
    python:
  File "renpy/ast.py", line 923, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "renpy/python.py", line 2235, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "renpy/common/00start.rpy", line 191, in <module>
    renpy.execute_default_statement(True)
  File "renpy/exports.py", line 3749, in execute_default_statement
    i.set_default(start)
  File "game/script.rpy", line 19, in set_default
    default lupDate = false
  File "renpy/python.py", line 2259, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 19, in <module>
    default lupDate = false
NameError: name 'false' is not defined

Windows-7-6.1.7601-SP1
Ren'Py 7.4.8.1895
AnimalSpeedDating 1.0
Sat Aug 21 20:11:06 2021
